name: Python Flask Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
    
    - name: Initialize database
      run: |
        python -c "from DAL import create_tables; create_tables()"
        python init_db.py
    
    - name: Run tests
      run: |
        python -m pytest -v tests/
      env:
        PYTHONPATH: ${{ github.workspace }}